version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
     - ./:/cook-pod-front
     - /cook-pod-front/node_modules
    command: sh -c "npm start"
    ports:
     - "3000:3000"
    networks:
      - cook_pod_front
  nginx:
    image: 921126570142.dkr.ecr.us-west-2.amazonaws.com/cook_pod_nginx:latest
    depends_on:
      - web
    environment:
      WORKER_PROCESSES: 2
      WORKER_CONNECTIONS: 1024
      KEEPALIVE_TIMEOUT: 65
      GZIP: "on"
      BACKEND_HOST: 172.26.0.2:3000
      BACKEND_MAX_FAILS: 3
      BACKEND_FAIL_TIMEOUT: 10s
      SERVER_PORT: 80
      LOG_STDOUT: "true"
    ports:
      - "80:80"
    networks:
      - cook_pod_front
networks:
  cook_pod_front:
    external: true
