version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
     - ./:/cook-pod-front
     - /cook-pod-front/node_modules
    command: sh -c "npm start"
    ports:
     - "3000:3000"
